# Variables for compiler and flags
CXX = g++
CXXFLAGS = -g -Wall -Iinclude

# List your source files here
SRCS = ./challenge_9.cc lib/MathTools.cc lib/XorTools.cc lib/NumberSystem.cc lib/Utils.cc lib/AES.cc 

# Define the output executable name (Linux doesn't require .exe extensions)
TARGET = pkcs_pad 

# The default 'recipe' that runs when you type 'make'
all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET)

# A 'clean' rule to delete the executable and start fresh
clean:
	rm -f $(TARGET)
